apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: butterfly-1
  annotations:
    # lego ssl cert
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - butterfly-1.flowlog-stats.com
    secretName: butterfly-1
  rules:
  - host: butterfly-1.flowlog-stats.com
    http:
      paths:
      - path: /
        backend:
          serviceName: butterfly-1
          servicePort: 57575
